<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZZE Crypto Signals</title>
    <link rel="stylesheet" href="styles.css">
    <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-auth.js"></script>
    <script defer src="app.js"></script>
</head>
<body>
    <header>
        <h1>ZZE Crypto Signals</h1>
        <nav>
            <button id="loginBtn">Login</button>
            <button id="logoutBtn" style="display:none;">Logout</button>
        </nav>
    </header>
    
    <section id="crypto-signals">
        <h2>Live Crypto Signals</h2>
        <table id="signal-table">
            <tr>
                <th>Crypto Pair</th>
                <th>Signal</th>
                <th>Timestamp</th>
            </tr>
        </table>
    </section>

    <section id="live-price">
        <h2>Live Bitcoin Price:</h2>
        <iframe src="https://widgets.coingecko.com/coingecko-coin-price-chart-widget.html?coin_id=bitcoin&currency=usd" width="100%" height="400"></iframe>
    </section>

    <section id="alerts">
        <h2>Subscribe for Alerts</h2>
        <input type="email" id="email" placeholder="Enter your email">
        <button onclick="subscribeAlert()">Subscribe</button>
    </section>
</body>
</html>body { 
    font-family: Arial, sans-serif; 
    text-align: center; 
    margin: 0; 
    padding: 0; 
}

header { 
    background: #333; 
    color: white; 
    padding: 10px; 
    display: flex; 
    justify-content: space-between; 
    align-items: center; 
}

table { 
    width: 90%; 
    margin: auto; 
    border-collapse: collapse; 
}

th, td { 
    border: 1px solid black; 
    padding: 10px; 
}

th { 
    background-color: #f2f2f2; 
}

button { 
    padding: 10px 15px; 
    margin: 5px; 
}const firebaseConfig = {
    apiKey: "YOUR_FIREBASE_API_KEY",
    authDomain: "YOUR_FIREBASE_AUTH_DOMAIN",
    projectId: "YOUR_FIREBASE_PROJECT_ID",
    storageBucket: "YOUR_FIREBASE_STORAGE_BUCKET",
    messagingSenderId: "YOUR_FIREBASE_MESSAGING_SENDER_ID",
    appId: "YOUR_FIREBASE_APP_ID"
};
firebase.initializeApp(firebaseConfig);

const auth =
